### ISSUE TITLE
integrate sTeX plugin into MMT/MathHub

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#10]
I guess we need to make a 
* cpan module
* set up travis  for the plugin repository
* adapt lmh setup procedures (and remove the LaTeXML branch) 
* ... what else? ...

**Comment by kohlhase** [comment]
I am re-assigning this to Christian.

**Comment by kohlhase** [comment]
The plugin seems to work in general (except for #12), so we can start making progress on this. 
It would be good if @dginev could give advice here. 
Once this works, I can remove the LaTeXML binding from the sTeX distribution and make a release for TeXLive. It would be good if we could do that before the end of Feb, so that that gets into TeXLive2016 so it can start percolating into distributions.

**Comment by cmaeder** [comment]
OK, I'll start adding travis tests to this repo

**Comment by kohlhase** [comment]
great.

**Comment by kohlhase** [comment]
#12 is fixed. So we should go full steam ahead with the integration.

**Comment by kohlhase** [comment]
I have moved out some of the files that do not really belong into the sTeX plugin into the LaTeXML-Plugin-KWARC (see https://github.com/KWARC/LaTeXML-Plugin-KWARC). This needs to be integrated into MMT as well.

**Comment by kohlhase** [comment]
The same holds for aTeXML-Plugin-sTeX-experimental (see https://github.com/KWARC/LaTeXML-Plugin-experimental), which I will make now. (see #7)

**Comment by kohlhase** [comment]
Actually that is not true, the experimental stuff should not be needed.

**Comment by cmaeder** [comment]
In https://github.com/KWARC/localmh/blob/latexml_plugin_stex/.travis.yml I install the two plugins manually into lmh. The HelloWorld examples run fine https://travis-ci.org/KWARC/localmh/builds/102412992 (but I need to check if the plugins properly override LaTeXML stuff).

@kohlhase could you make an sTeX branch without the files that are no longer needed?

Using brucemiller/LaTeXML instead of KWARC/LaTeXML does not work (although travis wrongly signals `passed`)  https://travis-ci.org/KWARC/localmh/builds/102413240

**Comment by kohlhase** [comment]
> @kohlhase could you make an sTeX branch without the files that are no longer needed?

will do ASAP.

**Comment by dginev** [comment]
Switching over to the master LaTeXML won't be that simple, there are important differences between the forks still. You probably need both me and Bruce looking at the forks before the plugin can properly switchover to master.

**Comment by kohlhase** [comment]
that was what I understood, but switching to master LaTeXML is not on the critical path to integration in to MMT and LMH. I guess your comment belongs into #8

**Comment by kohlhase** [comment]
> @kohlhase could you make an sTeX branch without the files that are no longer needed?

that is now branch ```noltxml```.

**Comment by cmaeder** [comment]
thanks, let's see if it works https://travis-ci.org/KWARC/localmh/builds/102429098

**Comment by cmaeder** [comment]
The plugins do not override yet, so the tests are obsolete.

**Comment by cmaeder** [comment]
Interestingly https://travis-ci.org/KWARC/sTeX/builds/102426557 still went through. (I would expect that a crippled branch should fail, but this does also not belong to this issue)

**Comment by cmaeder** [comment]
https://travis-ci.org/KWARC/localmh/builds/102435316 looks good

**Comment by cmaeder** [comment]
https://travis-ci.org/KWARC/localmh/builds/102599462 shows the (minor) differences compared to the old .omdoc files. @tkw1536 knows what do for lmh https://github.com/KWARC/localmh/issues/280

**Comment by kohlhase** [comment]
That is probably progress. I should check.

**Comment by cmaeder** [comment]
The creator became longer

```
<span xmlns="http://www.w3.org/1999/xhtml" class="ltx_text">miko</span>
```

and `xml:lang="de"` attributes are added to `omdoc:rendering`. 

I'm not sure if this attribute should got into `omdoc:CMP` of `helloworld.en.omdoc`

**Comment by cmaeder** [comment]
The few differences on the `for` attribute in `omdoc:definition` elements are due to https://github.com/KWARC/sTeX/issues/71

**Comment by cmaeder** [comment]
Can this issue be closed? Would it make sense to also make a KWARC/LaTeXML branch without the stuff that has been moved to the plugins?

**Comment by kohlhase** [comment]
This can be closed now.
