### ISSUE TITLE
add sTeX tests

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#11]
We currently do not seem to have tests. But we should develop some. @dginev please advise

There seems to be an sTeX test in the KWARC branch of LaTeXML (```921_stex.t```), that should be moved to the plugin.

**Comment by kohlhase** [comment]
I am starting two put tests files down in ```prototests/smglom``` and sister tests. This should eventually be made into real tests in the test harness.

**Comment by angerhang** [comment]
I added some test files via d186024ce04dd2f9e1ca39b7134d29228fa64ee5 along with the Makefiles which show commands I used. @kohlhase do you think we need more coverage? Or should we turn them into real tests already?

**Comment by kohlhase** [comment]
> @kohlhase do you think we need more coverage? Or should we turn them into real tests already?

this is a very good first set of tests. The idea about these is that we will work on them continuously, whenever there is an error we fix, we write a test for it (as part of the debugging effort), which will then test whether this regression comes back.

**Comment by kohlhase** [comment]
do these tests run automatically on ```make test```? and with ```cpanm```?

**Comment by angerhang** [comment]
No I don't think they run with `make test` and `cpanm` yet.

But I can do this today.

**Comment by kohlhase** [comment]
that was actually the main task of this issue :-).

**Comment by angerhang** [comment]
@dginev we probably need your help here.
Via 5814abd4fd6883caa321feddd35fd61a17bd2cfb, we have `t/*` integrated with `test_dynamic`. 

I also introduced a new [test.pm](https://github.com/KWARC/LaTeXML-Plugin-sTeX/blob/testcase/lib/sTeXTest.pm) which does `make` in different submodules. However this leads to the change for command when invoking. We have to provide with the `-Ilib` option now.

Do you think this is the right one of doing sTeX? 

If not, what changes would you suggest?

**Comment by dginev** [comment]
Makefile shouldn't be version-controlled, but auto-generated via "perl Makefile.PL" during the build step.

You shouldn't need the extra step, or the extra test.pm, looks like a hack to me.

Can't you simply borrow the setup I've arranged at say the MWS plugin? https://github.com/KWARC/LaTeXML-Plugin-MathWebSearch/ 

it has a sample test case as well.

**Comment by angerhang** [comment]
Thanks for the hints. I will adapt changes based on what you have for MWS plugin then : )
