### ISSUE TITLE
how to integrate XSLTs?

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#3]
I have copied the XSLTs over from sTeX, but they use the LaTeXML XSLTs. If I understand the idea of a plugin correctly, then the XSLTs will just be mixed into LaTeXML, so that finding them is not a problem?

**Comment by dginev** [comment]
Right, they should just work, since the LaTeXML xslts ought to be automatically detectable - that's a big part of the reason Bruce worked on the catalogue inclusions in the past.

**Comment by kohlhase** [comment]
OK, thanks.
