### ISSUE TITLE
allow \inlinedef omtext environment

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#37]
_From @kohlhase on October 17, 2015 8:38_

In ```MiKoMH/GenCS/source/SML/en/SML-rtfm.omdoc``` we get the error ```malformed: \inlinedef outside a statement!``` when transforming with ```latexml```, even though ```pdflatex``` accepts this. 

The offending part is 
```
    \begin{omtext}
      \inlinedef{\defi{RTFM} (\hateq ``read the fine manuals''})
    \end{omtext}
```
I am not sure why this is, since in ```statemts.sty.ltxml``` the conditional is 
```
 my $statement_ancestor = $document->findnode('./ancestor::omdoc:CMP/..', $original_node);
```
and an ```omtext``` environment certainly generates a CMP. Could this be a timing issue? 

_Copied from original issue: KWARC/sTeX#150_

**Comment by kohlhase** [comment]
_From @angerhang on October 22, 2015 0:15_

This does seem to be a timing issue for two reasons:
```tex
\begin{example}
      \inlinedef[for={Boolsort,BoolTrueConst,BoolFalseConst}]
\end{example}
```
in `MiKoMH/GenCS/source/adt/en/adt-def.tex` has no problem finding CMP, so the findnode is able to find `omdoc:CMP` if there is one.

And the second reason what you said: `CMP` exists in the final output.

**Comment by kohlhase** [comment]
so, can you solve it?

**Comment by kohlhase** [comment]
_From @angerhang on October 23, 2015 0:17_

Actually I suspect in `omtext.sty.ltxml` if
```
Tag('omdoc:CMP', autoClose=>1, autoOpen=>1);
```
is openning `omdoc:CMP` early enough @dginev ?

How can we make `CMP` open more promptly?

This is part of the `$document` at the time of `findNode`
```xml
  <para xmlns="http://dlmf.nist.gov/LaTeXML" _autoclose="1" _box="LaTeXML::Core::Whatsit=HASH(0x9016258)" _font="Font[serif,medium,upright,10,black,white,1,T1,de,*,*]" _vertical_mode_="1" xml:id="SML-rtfm.omgroup2.p1"/>
  <omtext _box="LaTeXML::Core::Whatsit=HASH(0x987b158)" _font="Font[serif,medium,upright,29.8,black,white,1,T1,de,*,*]" about="#SML-rtfm.omgroup2.omtext3" stex:srcref="/path/to/localmh/MathHub/MiKoMH/GenCS/source/SML/en/SML-rtfm.tex#textrange(from=6;1,to=6;19)" xml:id="SML-rtfm.omgroup2.omtext3"/>
</omgroup>
```
`CMP` is clearly not present.

**Comment by angerhang** [comment]
It is indeed a timing issue. 

Using the `inline-fix` branch. I think `symbol` element is being inserted correctly now, unless I am mistaken. You can see the place of insert at https://github.com/KWARC/LaTeXML-Plugin-sTeX/commit/5566e660dea07411960d6cc1d46f8367eb4d77e1.
 
We now have 
```shell
Hangs-MBP:en Hang$ latexmlc --profile stex-slides-module  --preamble ../../../../meta-inf/lib/pre.tex --postamble ../../../../meta-inf/lib/post.tex SML-rtfm.tex
 --path ../../../../../../ext/sTeX/sty/etc/ --path ~/kwarc/LaTeXML-Plugin-Doc/testing/WML/ --log test.ltxlog  > test.omdoc

(Finalizing... 0.00 sec)
Conversion complete: No obvious problems.

(post-processing...
(Scan  processing... 0.00 sec)
(CrossRef  processing... 0.00 sec)
(XMath[w/OpenMath+MathML::Presentation]  processing... 0.00 sec)
(XSLT[using omdocpost.xsl]  processing... 0.00 sec) 0.00 sec)
Post-processing complete: No obvious problems
processing finished Mon Feb 15 14:39:10 2016
Status:conversion:0 
```

```xml
Hangs-MBP:en Hang$ cat test.omdoc 
......
<dc:title xml:id="SML-rtfm.omgroup2.metadata1.title1" about="#SML-rtfm.omgroup2.metadata1.title1" stex:srcref="MiKoMH/GenCS/source/SML/en/SML-rtfm.tex#textrange(from=4;0,to=4;53)">For more information on <om:OMOBJ stex:srcref="MiKoMH/GenCS/source/SML/en/SML-rtfm.tex#textrange(from=0;1,to=0;0)"><om:OMS cd="SML-basics" name="SMLlanguage"/></om:OMOBJ></dc:title>
      </omdoc:metadata>
      <symbol xmlns="" name="RTFM" xml:id="RTFM.def.sym"/>
      <omdoc:omtext xml:id="SML-rtfm.omgroup2.omtext3" about="#SML-rtfm.omgroup2.omtext3" stex:srcref="MiKoMH/GenCS/source/SML/en/SML-rtfm.tex#textrange(from=6;1,to=8;16)" class="ltx_centering">
        <omdoc:CMP xml:id="SML-rtfm.omgroup2.omtext3.CMP1" about="#SML-rtfm.omgroup2.omtext3.CMP1" stex:srcref="MiKoMH/GenCS/source/SML/en/SML-rtfm.tex#textrange(from=6;1,to=7;63)">
<p xmlns="http://www.w3.org/1999/xhtml" id="SML-rtfm.omgroup2.omtext3.CMP1.p1" class="ltx_p" about="#SML-rtfm.omgroup2.omtext3.CMP1.p1" stex:srcref="MiKoMH/GenCS/source/SML/en/SML-rtfm.tex#textrange(from=6;1,to=7;63)"><span class="ltx_text inlinedef" style="font-size:298%;"><omdoc:term cd="SML-rtfm" name="RTFM" role="definiendum" xml:id="SML-rtfm.omgroup2.omtext3.CMP1.p1.term1" about="#SML-rtfm.omgroup2.omtext3.CMP1.p1.term1" stex:srcref="MiKoMH/GenCS/source/SML/en/SML-rtfm.tex#textrange(from=0;1,to=0;0)">RTFM</omdoc:term> (&#x2259; &#x2018;&#x2018;read the fine manuals&#x2019;&#x2019;</span><span class="ltx_text" style="font-size:298%;">)</span></p></omdoc:CMP>
      </omdoc:omtext>
    </omdoc:omgroup>
  </omdoc:theory>
...
```
Run without problem although the segmentation fault still remains.

**Comment by kohlhase** [comment]
looks good, please merge

**Comment by kohlhase** [comment]
this does not work yet, on ```MathHub/MiKoMH/GenCS/latexml/encryption/en/public-key-encryption.tex``` I get 
```
error: latexml-compiler: malformed: \inlinedef outside a statement!
error: latexml-compiler: malformed: \inlinedef outside a statement!
```

**Comment by kohlhase** [comment]
this seems to work

**Comment by kohlhase** [comment]
I have to reopen, there are a couple of cases where this is still a problem. E.g. ```MathHub/MiKoMH/GenCS/source/encryption/en/encryption.tex``` which has 
```
  \begin{example}[title=Spartan encryption (since ca. 700 BC)]\strut\\
      \begin{columns}
        \begin{column}{7.5cm}
          The oldest (military) encryption method is a \inlinedef{\defi{scytale} -- a
            wooden stick of defined diameter, onto which a strip of parchment with letters
            can be wrapped to reveal the plaintext}. Here the stick is the key and the
          parchment strip the ciphertext.
        \end{column}
        \begin{column}{4cm}
          \mhcgraphics[width=4cm]{encryption/PIC/scytale}
        \end{column}
      \end{columns}
    \end{example}
  ```
I guess the ```column```s interfere here, maybe the code should look for ancestors?

**Comment by kohlhase** [comment]
but maybe it is just the ```example``` environment? In ```MathHub/MiKoMH/GenCS/source/websearch/en/queries.tex``` I have 
```
    \begin{example}[id=multiword-query,for=websearch-query.def]
      Most web search engines accept \inlinedef{\adefii{multiword
          queries}{multiword}{query}, i.e.  multisets of strings (words)}.
    \end{example}
```
and it also gives an error.

**Comment by kohlhase** [comment]
I seem to have fixed this myself.

**Comment by kohlhase** [comment]
actually, I have to reopen again, this time, ```MathHub/MiKoMH/GenCS/latexml/machines/en/build-RM-intro.tex``` is the culprit, it has two inlinedefs in the omtext at line 97. It gives the inlinedef error. 
Please have a look (I cannot find the problem).

**Comment by angerhang** [comment]
In fact this doesn't result from two `inlinedef` in one line, but rather an `inlinedef` appears first in the `omtext` without any text in the front 
```
\begin{omtext}
    \inlinedef{In this architecture (called the \defii{register}{machine} architecture)},
    programs are sequences of $2n$-bit numbers. The first $n$-bit part encodes the
    instruction, the second one the argument of the instruction. The
    {\twintoo{program}{counter}} addresses \inlinedef{the \defii{current}{instruction}
      (operation + argument)}.
  \end{omtext}
```

The pull request should fix it, and I added some test cases as well.

One other remark is that when we have more than one `inlinedef` in a `omtext`, `axiom` and others, we run into `xml:id` validity issues as well  https://github.com/KWARC/LaTeXML-Plugin-sTeX/issues/23

**Comment by kohlhase** [comment]
I think that you should make the id problems a separate issue and close this one.

**Comment by kohlhase** [comment]
especially, since #23 is closed.

**Comment by angerhang** [comment]
Closing, but #23 is still open, I shall just make a comment in that issue.
