### ISSUE TITLE
Missing packages for fresh plugin installation 

### ISSUE THREAD

**Issue by angerhang** [KWARC/LaTeXML-Plugin-sTeX#54]
For a fresh sTeX plugin installation, there are five packages that seem to be missing

```
Error:missing_file:lststex Can't find package lststex
	Anonymous String#textrange(from=0;1,to=0;0)
	search paths are /Users/Hang/lmh/localmh/MathHub/smglom/graphs/source
	Input is empty

Error:missing_file:lstomdoc Can't find package lstomdoc
	Anonymous String#textrange(from=1;1,to=1;0)
	Input is empty

Error:missing_file:ded Can't find package ded
	Anonymous String#textrange(from=2;1,to=2;0)
	Input is empty

Error:missing_file:calbf Can't find package calbf
	Anonymous String#textrange(from=3;1,to=3;0)
	Input is empty

Error:missing_file:ed Can't find package ed
	Anonymous String#textrange(from=4;1,to=4;0)
	Input is empty
```
which we should think of a way for distribution either let them be part of the plugin or distribute them separately as @dginev mentioned in #6 .

**Comment by kohlhase** [comment]
These files are in https://github.com/KWARC/LaTeXML-Plugin-KWARC, This should be installed by ```lmh setup --install``` (you may need to remove the ```localmh/ext``` directory first) modulo https://github.com/KWARC/localmh/issues/294

**Comment by kohlhase** [comment]
closing, since this is just an installation/update glitch

**Comment by angerhang** [comment]
Ok thanks for pointing that out.

**Comment by angerhang** [comment]
Oh I understand now! 

I thought we also wanted to do the development using the `LaTeXML-Plugin-sTeX` outside docker but we are still using the old workflow inside docker right?

Just one more question about testing the plugin, it seems to me that there are still two files missing after installed `LaTeXML-Plugin-KWARC`:
```
Initialization complete: 2 errors; 2 missing files[calbf.sty, lstomdoc.sty]. Aborting.
```

More concretely:
```
InputDefinitions('lstomdoc',type=>'sty',noltxml=>1); 
```
the raw TeX files are used here but cannot be found.

**Comment by kohlhase** [comment]
oh, interesting. They are part of sTeX: they are at ```.../sTeX/sty/etc```. You have to set your ```TEXINPUTS``` to use ```.../sTeX/sty//:...```.

**Comment by angerhang** [comment]
Yes that's right. 

We probably also want to update the texlive distribution while we do the cpan submission don't we?

**Comment by kohlhase** [comment]
yes, we do, but that needs some more testing and documentation.
