### ISSUE TITLE
how to use, deploy and test the plugin? 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#6]
I think I am nearing a first workable plugin, and I would like to try it out. Is it correct that I must 
```make; make install``` and then I can just use it with 
```latexml --profile=stex-modules.opt xxx.tex```
What is the role of ```cpanm```?

**Comment by kohlhase** [comment]
And then how would I integrate this into the MMT-based workflows? How does the plugin know that it should use the KWARC branch? ...

**Comment by kohlhase** [comment]
do I understand correctly that we need to somehow submit the plugin for cpanm once it is ready?

**Comment by dginev** [comment]
Right, the usual Perl incantations apply for the installation:
```
 perl Makefile.PL ; make ; make test ; make install
 ```

if one uses cpanm, there is a synonym for that that looks like:
```
 cpanm .
```

Once installed, you should simply use LaTeXML as you showed.

To register the plugin centrally with CPAN, it indeed needs to be submitted, which I can either do for you, or you can obtain a PAUSEID and do by hand (the UI there is a bit arcane): http://pause.perl.org

As to the KWARC fork of LaTeXML - the right flow there is to first install the fork, and then install the plugin. If no LaTeXML is installed the regular installation will fail, whereas installing via cpanm will fetch the LaTeXML registered under CPAN, which is the 0.8.1 release.

Another useful idiom is sometimes installing directly from the git repository with a single command, which looks like:
```
cpanm git://github.com/KWARC/LaTeXML-Plugin-sTeX.git
```

One thing to keep in mind is where the installation step copies over the files, and you should use the same toolchain for both latexml and its plugins to have a sane setup. That's the main reason I always use ```cpanm``` nowadays, as it allows for both easy development and installation without sudo, which avoids a lot of headaches.

**Comment by kohlhase** [comment]
thanks for the instructions. If I understand correctly, then we should now test the plugin locally and when it runs, we can submit it to cpanm cental. I would like to take you up on your offer. to do that for me. What is the workflow for updating the plugin? Can I do that myself (or in fact @angerhang) after you registered?

**Comment by kohlhase** [comment]
I still do not understand. I ran ```cpanm . ``` and that seemed to to something in the ```blib``` subdir (after I installed ```(local::lib)``` as it told me to. But how do I run ```latexmlc``` with that?

**Comment by angerhang** [comment]
I followed Deyan's instructions and was able to run the plugin successfully by using 
```
cpanm .
```
although there were a few test case failures which I don't know if they matter or not.


I ran `latexmlc` like the following after installed `(local::lib)`
```shell
MacBook-Pro:Profiles yuancalvin$ latexmlc --profile=stex.opt test.tex 
(Loading profile /Users/yuancalvin/LaTeXML-Plugin-sTeX/lib/LaTeXML/resources/Profiles/stex.opt... )
(Loading profile /Users/yuancalvin/LaTeXML-Plugin-sTeX/lib/LaTeXML/resources/Profiles/stex.opt... )

(Loading /Library/Perl/5.18/LaTeXML/Package/TeX.pool.ltxml...
(Loading /Library/Perl/5.18/LaTeXML/Package/eTeX.pool.ltxml... 0.01 sec)
(Loading /Library/Perl/5.18/LaTeXML/Package/pdfTeX.pool.ltxml... 0.01 sec) 0.16 sec)
latexmlc (LaTeXML version 0.8.1 (KWARC fork); revision ffe9390)
processing started Sun Jan  3 22:19:50 2016

(Digesting TeX test...

(Processing content /Users/yuancalvin/LaTeXML-Plugin-sTeX/lib/LaTeXML/resources/Profiles/test.tex... 0.00 sec) 0.00 sec)
(Building...
(Loading compiled schema /Library/Perl/5.18/LaTeXML/resources/RelaxNG/LaTeXML.model... 0.01 sec) 0.02 sec)
(Rewriting... 0.00 sec)
(Finalizing... 0.00 sec)
Conversion complete: No obvious problems.
Status:conversion:0 
<?xml version="1.0" encoding="UTF-8"?>
```

**Comment by dginev** [comment]
If there were any errors during ```cpanm .```, then the plugin failed to install - cpanm aborts installation on errors.

Looking at your example run, you indeed loaded the profile from the current directory (not from an installation cpanm directory), so latexmlc failed to load any real sTeX bindings in that run.

I haven't checked how far the plugin work has gone, but ```cpanm .``` should execute without errors for you to even have a working setup.

**Comment by dginev** [comment]
Btw, if either of you hasn't setup cpanm for non-root development before, this may be the easiest tutorial: http://privacygeek.blogspot.bg/2013/03/the-worlds-easiest-guide-to-installing.html

In essence, it all boils down to including the output of:
```
perl -I ~/perl5/lib/perl5 -Mlocal::lib
```

in your ~/.bashrc (or equivalent) file, so that Perl knows about the local user paths created by cpanm.

**Comment by angerhang** [comment]
Thanks for the nice tutorial.

You are right, LaTeXML was loading from the current directory, because I was calling the latexml in the profiler directory. After I moved out, it seems to load properly. `cpanm` installed the plugin without any error. It was for KWARC's LaTeXML that I ran into some problems.

I think we are on the right track for testing
```
MacBook-Pro:test yuancalvin$ latexmlc --profile=stex-omdoc-modules.opt test.tex 
(Loading profile /Library/Perl/5.18/LaTeXML/resources/Profiles/stex-omdoc-modules.opt... )
(Loading profile /Library/Perl/5.18/LaTeXML/resources/Profiles/stex-omdoc-modules.opt... )

(Loading /Library/Perl/5.18/LaTeXML/Package/TeX.pool.ltxml...
(Loading /Library/Perl/5.18/LaTeXML/Package/eTeX.pool.ltxml... 0.00 sec)
(Loading /Library/Perl/5.18/LaTeXML/Package/pdfTeX.pool.ltxml... 0.00 sec) 0.15 sec)
(Loading /usr/local/texlive/2015/texmf-dist/tex/latex/stex/omdoc/omdoc.cls.ltxml...
(Loading /Library/Perl/5.18/LaTeXML/Package/article.cls.ltxml...
(Loading /Library/Perl/5.18/LaTeXML/Package/LaTeX.pool.ltxml... 0.19 sec) 0.20 sec)
(Loading /usr/local/texlive/2015/texmf-dist/tex/latex/stex/sref/sref.sty.ltxml...
(Loading /usr/local/texlive/2015/texmf-dist/tex/latex/stex/metakeys/metakeys.sty.ltxml... 0.00 sec) 0.11 sec)
(Loading /usr/local/texlive/2015/texmf-dist/tex/latex/stex/omdoc/omdoc.sty.ltxml...
(Loading /Library/Perl/5.18/LaTeXML/Package/xspace.sty.ltxml... 0.00 sec)
(Loading /usr/local/texlive/2015/texmf-dist/tex/latex/stex/omtext/omtext.sty.ltxml... 0.11 sec) 0.33 sec) 0.85 sec)
(Loading /Library/Perl/5.18/LaTeXML/Package/amsmath.sty.ltxml...
(Loading /Library/Perl/5.18/LaTeXML/Package/amsbsy.sty.ltxml... 0.00 sec)
(Loading /Library/Perl/5.18/LaTeXML/Package/amstext.sty.ltxml... 0.00 sec)
(Loading /Library/Perl/5.18/LaTeXML/Package/amsopn.sty.ltxml... 0.00 sec) 0.04 sec)
(Loading /Library/Perl/5.18/LaTeXML/Package/amssymb.sty.ltxml...
(Loading /Library/Perl/5.18/LaTeXML/Package/amsfonts.sty.ltxml... 0.00 sec) 0.02 sec)
(Loading /Library/Perl/5.18/LaTeXML/Package/eurosym.sty.ltxml... 0.00 sec)
(Processing definitions /usr/local/texlive/2015/texmf-dist/tex/latex/wasysym/wasysym.sty... 0.07 sec)
(Loading /Library/Perl/5.18/LaTeXML/Package/multirow.sty.ltxml... 0.00 sec)
(Loading /Library/Perl/5.18/LaTeXML/Package/paralist.sty.ltxml... 0.02 sec)
Error:missing_file:lststex Can't find package lststex
	Anonymous String#textrange(from=0;1,to=0;0)
	search paths are /Users/yuancalvin/test
	Input is empty

Error:missing_file:lstomdoc Can't find package lstomdoc
	Anonymous String#textrange(from=1;1,to=1;0)
	Input is empty

Error:missing_file:ded Can't find package ded
	Anonymous String#textrange(from=2;1,to=2;0)
	Input is empty

Error:missing_file:calbf Can't find package calbf
	Anonymous String#textrange(from=3;1,to=3;0)
	Input is empty
```

Also we still need to add a few more paths to the profilers since some packages are supposed 
to be preloaded and their paths are not specified.

**Comment by dginev** [comment]
Right, having sTeX in your texlive distro is bound to cause all kinds of problems when developing. If I were you I would remove that entirely:
```
rm -rf /usr/local/texlive/2015/texmf-dist/tex/latex/stex
```

If this plugin takes off, I'd hope that the LaTeXML bindings also don't get distributed with texlive, but via CPAN instead.

The missing packages seem to be the ones distributed under the ```etc/``` directory, which @kohlhase should advise whether to be a part of this plugin, or shipped separately.

**Comment by kohlhase** [comment]
> If this plugin takes off, I'd hope that the LaTeXML bindings also don't get distributed with texlive, but via CPAN instead.

Indeed, this is exactly what I am hoping. This plugin is currently a bit behind the sTeX head, but if we can get it running in general, I will gladly update it and release the next sTeX version without the ltxml stuff. Then it will be only a couple of years until they disappear from the TeXLive wild.

**Comment by kohlhase** [comment]
I seem to have also installed things and am testing with ```prototests/smglom``` (see #11). I will close here and put the rest of my problems into other issues.
