### ISSUE TITLE
output provided stex theories

### ISSUE THREAD

**Issue by cmaeder** [KWARC/LaTeXML-Plugin-sTeX#63]
write a line "provides: URI" into the log file (for pdflatex/xelatex and latexml)

**Comment by kohlhase** [comment]
I guess with URI you mean the MMT URI. 
And I guess that the best place to do that is during the ```\end{module}```, so that we only crow when we are really succesful.

**Comment by cmaeder** [comment]
it is called `MPath` on my side.

**Comment by cmaeder** [comment]
`MPath` is a `DPath` and a local name.

**Comment by kohlhase** [comment]
can you give an example? 

Michael

**Comment by cmaeder** [comment]
MPath:  `http://cds.omdoc.org/examples?Bool`

**Comment by cmaeder** [comment]
(`Bool` is the local name and the parent DPath is `http://cds.omdoc.org/examples`)

**Comment by kohlhase** [comment]
I made something, but it does not quite work, but I must say that I think that we do not need this for the pdf generation. Nothing will read the pdf and build on top of it. We really need this for the latexml side of things. I will make the respective ticket there.

**Comment by kohlhase** [comment]
Ah, I was already here, and had thought I was on the pdf side, sorry. I am actually going to re-assign this to Hang, who can probably do this quite quickly. @angerhang could you pleae make this a priority? It should be simple to do.

**Comment by angerhang** [comment]
Given
```tex
Hangs-MacBook-Pro:en Hang$ cat test.tex 
\begin{module}[id=test]
\importmhmodule[path=dmath/en/newTest]{newTest}
\end{module}
```

We get 
```xml
Info:provides: URI: MiKoMH/GenCS/dmath/en/newTest?test
	/Users/Hang/lmh/localmh/MathHub/MiKoMH/meta-inf/lib/pre.tex#textrange(from=4;0,to=4;16)
```
via 5277c8f0bdbb98f9007ea547964cce8f476bbb7c.

**Comment by kohlhase** [comment]
very nice, that is what we need (for the moment). The XMLbase stuff is less of a priority, so I will close this ticket and make a new one for XMLBase.

**Comment by angerhang** [comment]
I think I forgot to consider the situation where there are multiple `\importmodule`s. 

In this case do we want to have a single `provides: URI` or do we want to have one `provides: URI` for every module imported?

**Comment by kohlhase** [comment]
no, importmodule should not generate anything.

**Comment by angerhang** [comment]
I meant `\importmhmodule`. It is still possible to have several of them in one single module.

**Comment by kohlhase** [comment]
yes, but none of them should give any output at all.

**Comment by cmaeder** [comment]
> Hangs-MacBook-Pro:en Hang$ cat test.tex 
> \begin{module}[id=test]
> \importmhmodule[path=dmath/en/newTest]{newTest}
> \end{module}
> 
> We get
> 
> Info:provides: URI: MiKoMH/GenCS/dmath/en/newTest?test

Assuming that the file `test.tex` also lives in `MiKoMH/GenCS/dmath/en` should the URI not be 
`MiKoMH/GenCS/dmath/en/test?test` since `newTest` is only "used" to "provide" test?

(The literal string `URI:` was not supposed to be in the output but does not harm)

**Comment by kohlhase** [comment]
Ah, now I understand the question about the importmodule, this is a misunderstanding
given ```\begin{module}[id=bar]``` in ```<path>/foo.tex```, the ```\end{module}``` should trigger output 
```
providing theory: <path>/foo?bar
```

**Comment by kohlhase** [comment]
But when ```\importmodule...{baz}``` (and of course all derived macros) reads  a ```\begin/\end{module}``` it should do nothing.

**Comment by kohlhase** [comment]
If you have questions, just come by my office.

**Comment by angerhang** [comment]
Now we have 
```tex
Hangs-MacBook-Pro:en Hang$ pwd
/Users/Hang/lmh/localmh/MathHub/MiKoMH/GenCS/source/dmath/en
Hangs-MacBook-Pro:en Hang$ cat test.tex 
\begin{module}[id=myTest]

\end{module}

\begin{module}[id=newTest]

\end{module}
```

Which generates 
```xml
Info:provides theory: MiKoMH/GenCS/source/dmath/en/test?myTest
	/Users/Hang/lmh/localmh/MathHub/MiKoMH/meta-inf/lib/pre.tex#textrange(from=4;0,to=4;16)

Info:provides theory: MiKoMH/GenCS/source/dmath/en/test?newTest
	/Users/Hang/lmh/localmh/MathHub/MiKoMH/meta-inf/lib/pre.tex#textrange(from=4;0,to=4;16)
```

via 788a21bac68f154e821113069dbf051bd3bc929c

**Comment by kohlhase** [comment]
that is good. How about 
```
\begin{module}[id=myTest]
\importmodule[foo]{bar}
\end{module}
```
where ```foo.tex``` has a suitable module. This should only give
```
Info:provides theory: MiKoMH/GenCS/source/dmath/en/test?myTest
```

**Comment by angerhang** [comment]
Yes only one provides theory is generated.

**Comment by cmaeder** [comment]
This looks good.  A further question to @kohlhase. What would be the actual (or a suitable) `MPath` URI? Maybe `https://mathhub.info/MiKoMH/GenCS/dmath/en/test?myTest`? (This uses `\baseURI` from `localpaths.tex`.)

@angerhang Create a pull request and merge it as soon as Michael (or some other reviewer) types :+1 (`:+1`) into it (and travis tests went through).

**Comment by cmaeder** [comment]
looks fine for me :+1
