### ISSUE TITLE
Couldn't create DB cache

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#64]
I get the error 
```
error: latexml: no omdoc created
latexml-result: failure /Users/kohlhase/localmh/MathHub/MiKoMH/GenCS/latexml/www/en/www-overview.omdoc
error: latexml-post: internal:db Couldn't create DB cache for /Users/kohlhase/localmh/MathHub/MiKoMH/GenCS/latexml/www/en/www-overview.omdoc
```

@dginev, does this ring a bell?

**Comment by dginev** [comment]
Do you have write permissions to that directory? Also do you have libdb installed?

The error is that latexml's post-processing is failing to create a cache DB

**Comment by kohlhase** [comment]
Both dirs I have write permission. 

I guess I should have libdb installed, since the error is only for some of the files in that directory; it seems to work for the others.

**Comment by angerhang** [comment]
Strange I cannot reproduce
```
Hangs-MBP:GenCS Hang$ lmh omdoc source/www/en/www-overview.tex --force
sms-result: success /mounted/lmh/MathHub/MiKoMH/GenCS/source/www/en/url-urn.sms
latexml-result: success /mounted/lmh/MathHub/MiKoMH/GenCS/latexml/www/en/www-overview.omdoc
```
Did you switch back to the master branch after working on `LaTeXML-Plugin-sTeX` form yesterday?

**Comment by kohlhase** [comment]
> Strange I cannot reproduce

I was hoping that (then there is no general problem) and fearing that (then it is unlikely to be fixed for me)

**Comment by kohlhase** [comment]
> Did you switch back to the master branch after working on LaTeXML-Plugin-sTeX form yesterday?�

actually no, but this should not influence the error (I had seen that before).

**Comment by angerhang** [comment]
@kohlhase could you check on this ticket again? 

I still cannot reproduce.

**Comment by kohlhase** [comment]
this is still a problem when I run it locally on my mac, but I can run it fine in docker.
