### ISSUE TITLE
MMT environment 

### ISSUE THREAD

**Issue by angerhang** [KWARC/LaTeXML-Plugin-sTeX#67]
On the LaTeXML side, we are using `mmt.sty.ltxml` for `mmt` environment which is loaded if we set the `mmt` option.  Via 216b9e75bcbd1ef056b2a711cfea30969542f611

we can get 
``` 
<omdoc:theory xml:id="omdoc1.theory1" about="#omdoc1.theory1" stex:srcref="/Users/Hang/kwarc/LaTeXML-Plugin-sTeX/prototests/mmt/foo.tex#textrange(from=0;4,to=6;12)"><omdoc:metadata xml:id="omdoc1.theory1.metadata1" about="#omdoc1.theory1.metadata1" stex:srcref="/Users/Hang/kwarc/LaTeXML-Plugin-sTeX/prototests/mmt/foo.tex#textrange(from=0;4,to=6;12)"><dc:creator xml:id="omdoc1.theory1.metadata1.creator1" about="#omdoc1.theory1.metadata1.creator1" stex:srcref="/Users/Hang/kwarc/LaTeXML-Plugin-sTeX/prototests/mmt/foo.tex#textrange(from=0;4,to=6;12)"></dc:creator><dc:contributor xml:id="omdoc1.theory1.metadata1.contributor2" about="#omdoc1.theory1.metadata1.contributor2" stex:srcref="/Users/Hang/kwarc/LaTeXML-Plugin-sTeX/prototests/mmt/foo.tex#textrange(from=0;4,to=6;12)"></dc:contributor><omdoc:meta property="smglom:state" xml:id="omdoc1.theory1.metadata1.meta3" about="#omdoc1.theory1.metadata1.meta3" stex:srcref="/Users/Hang/kwarc/LaTeXML-Plugin-sTeX/prototests/mmt/foo.tex#textrange(from=0;4,to=6;12)"></omdoc:meta></omdoc:metadata>
  <div xmlns="http://www.w3.org/1999/xhtml" id="theory1.p1" class="ltx_para">
   <p id="theory1.p1.p1" class="ltx_p" about="#omdoc1.theory1.p1.p1">foo
   <omdoc:oref href="foo#MMT1" xml:id="omdoc1.theory1.p1.p1.oref1" about="#omdoc1.theory1.p1.p1.oref1" stex:srcref="/Users/Hang/kwarc/LaTeXML-Plugin-sTeX/prototests/mmt/foo.tex#textrange(from=2;0,to=4;9)"/>
      <span class="ltx_text mmt">
        a : b = c
      </span>
   This is somehitng
   </p>
</div></omdoc:theory>
```
from a module 
```
\begin{module}{foo}
\begin{mmt}
 a : b = c
\end{mmt}
This is somehitng
\end{module}
```

We then can use the postprocessor exact the span of class 'ltx_text mmt' into `foo.smo`.  

We can accomplish this in several ways:
1. Use XSLT 2.0 `result-document` which can directly generate multiple files at the same time. Unfortunately upgrading from 1.0 is painstaking so this is not the best option, although this is the most direct approach. 
2. Invoke the postprocessor twice, after we get the `foo.omdoc` and we again invoke the postprocessor on `foo.omdoc` to extract the `ltx_text_mmt` span into `foo.smo`. 

I think the second method seems more plausible. @kohlhase can you comment on this?

**Comment by angerhang** [comment]
I just finished the `mmt.xsl` that can extract mmt stuff from `foo.omdoc` 
```scala
//foo#MMT1
a : b = c
//end foo#MMT1
```

**Comment by angerhang** [comment]
In the `prototests/mmt` folder we can find several test files that simulate using MMT inside sTeX approach:

* `foo.tex` the MMT embedded sTeX
* `foo.smo` mixed omdoc after the initial LaTeXML transformation 
* `foo.mso` should be MMT only after being transformed by `mmt.xsl`
* `foo.omdoc` generated using `mmtCleanUp.xsl` which gets rid of the embedded MMT elements

**Comment by angerhang** [comment]
I have also included some other newly added features such as `\mmtr` and `\mmt` ...

@kohlhase what do you think of the current implementation and can you specify what we want for the new control sequences?

**Comment by kohlhase** [comment]
is this still relevant?

**Comment by angerhang** [comment]
No I don't think so. I talked about this and actually got rid of the `mmtCleanUp.xsl`. 
Closing...
