### ISSUE TITLE
What to do with the experimental files from the sTeX distribution?

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#7]
I have a few parts of the sTeX distribution that I consider experimental. For instance ```sty/reqdoc``` or ```sty/physml``` and that I do not really want to be part of the distribution any more. What is best to do with them? 

I might put them into their own repository/plugin?

**Comment by dginev** [comment]
I guess you could make a second plugin depending on this one, yes.

A different type of distinction is that the submission to CPAN is done via a make step that generates a manifest and then packs the repository into an archive that gets submitted. So you could take out all experimental files from the manifest and submit to CPAN only the core files. But that works only if the primary way of using sTeX is the CPAN flow, as opposed to the "git clone" flow.

**Comment by kohlhase** [comment]
How about another plugin: ```LaTeXML-Plugin-sTeX-experimental```, then I can just dump the files there and not lose them.

**Comment by cmaeder** [comment]
```
cpanm https://github.com/KWARC/LaTeXML.git
cpanm https://github.com/KWARC/LaTeXML-Plugin-sTeX.git
```

worked quite well on a fresh machine. However, `cpanm` needs to be a new version that supports git clone (according to https://github.com/miyagawa/cpanminus/blob/devel/Changes I assume this is version 1.7039). Therefore I had to setup up cpanm before with:

```
sudo apt-get install cpanminus
cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
cpanm App::cpanminus
export PATH=/home/maeder/perl5/bin:$PATH
```

A (further) `git clone https://github.com/KWARC/LaTeXML-Plugin-sTeX.git` was necessary to actually work with this repository.

**Comment by kohlhase** [comment]
this is probably the wrong issue (did you mean #10 ?)

**Comment by cmaeder** [comment]
Well, I thought, a CPAN submission is not that important.

**Comment by kohlhase** [comment]
I will make a LaTeXML-Plugin-sTeX-experimental (see https://github.com/KWARC/LaTeXML-Plugin-experimental) for these files. Then they are out of the way.
