### ISSUE TITLE
Make a meaningful and much more complete README.md

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#74]

**Comment by angerhang** [comment]
By this do you mean the documentation for how to do cpan release or for how to use `LaTeXML-Plugin-sTeX`?

**Comment by kohlhase** [comment]
no, how to use it, how to install it, what it does, where to find documentation, ...

**Comment by kohlhase** [comment]
well done, I reworked this a bit. closing.
