### ISSUE TITLE
integrate model make upon schema changes into Makefile

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#79]
If we change the RelaxNG schema under ```lib/LaTeX/resources/RelaxNG```, then we have to generate a new model ```omdoc+ltxml.model``` there. This is currently manually done via the ```Makefile``` there. That Make should be integrated in the general make mechanism. And I am not sure that it is, actually quite skeptical.

**Comment by angerhang** [comment]
Done closing....
