### ISSUE TITLE
integrate KWARC branch into sTeX plugin

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#8]
Deyan said that he would work with Bruce to integrate the specifics of the KWARC branch of LaTeXML that cannot be overwritten by the plugin into the LaTeXML core, and then add the rest of the KWARC branch here, so that we can close the KWARC branch.

**Comment by cmaeder** [comment]
Currently the "only" failures with the brucemiller/LaTeXML branch are:

```
error: latexml-compiler: missing_file:lstomdoc Can't find package lstomdoc
error: latexml-compiler: missing_file:calbf Can't find package calbf
```

see https://travis-ci.org/KWARC/localmh/builds/102659829

**Comment by dginev** [comment]
those files are either not present in the stex plugin, or the paths to them haven't been added to the stex profile file.

**Comment by kohlhase** [comment]
I made a plugin KWARC/LaTeXML-Plugin-KWARC for them. You should use that as well in the travis tests.

**Comment by cmaeder** [comment]
I've used LaTeXML-Plugin-KWARC, but maybe it was an older version. I'll rerun the test.

**Comment by kohlhase** [comment]
I have also moved subdirs around (but tried to fix things in the travis files. Please check that as well.

**Comment by cmaeder** [comment]
The current test https://travis-ci.org/KWARC/localmh/builds/103312245 fails now with many

```
latexml-compiler: stex:locator Locator "at /home/travis/build/KWARC/localmh/MathHub/HelloWorld/smglom/source/???.tex; line ?? col ??" is garbled, expect nonsense in stex:srcref ...
```

**Comment by kohlhase** [comment]
hmmm, It seems that it is compiling the ```lib``` subdir for some reason, that should not be the case. It chokes  on ```post.tex``` there (not surprising).

**Comment by cmaeder** [comment]
I believe, it is not traversing the `lib` subdir but it only takes `lib/post.tex` as postamble.

**Comment by kohlhase** [comment]
I tried running lmh omdoc locally, and I am not getting errors.

**Comment by cmaeder** [comment]
The errors occur for brucemiller/LaTeXML

**Comment by kohlhase** [comment]
Oh, but that was never expected to work, can you please switch back to the KWARC branch?

**Comment by cmaeder** [comment]
Am I on the wrong issue here? Maybe it should be #13

**Comment by kohlhase** [comment]
No, but the integration needs to be planned out by Deyan and Bruce, just testing is not going to work. It is a long-term thing.

**Comment by cmaeder** [comment]
the localmh master was fine 24 hours ago (and I'm just rebuilding it). The above errors occurred for my localmh brucemiller_latexml branch.

**Comment by kohlhase** [comment]
thanks for the clarification. I do not think that there is anything you can help here. We should just delete the branch from travis

**Comment by cmaeder** [comment]
right, the localmh diff is pretty trivial

```
--- a/lmh/data/config.json
+++ b/lmh/data/config.json
@@ -67,7 +67,7 @@
        "setup::latexml::source": {
                "type": "string",
                "help": "Default Source for latexml. ",
-               "default": "https://github.com/KWARC/LaTeXML.git"
+               "default": "https://github.com/brucemiller/LaTeXML.git"
        },
```

**Comment by kohlhase** [comment]
the discussion here has diverged, and we have the new #76 therefore I close this issue.
