### ISSUE TITLE
latexml postprocessing wrong path

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#83]
see https://github.com/KWARC/MMT/issues/146, We have a path problem.

**Comment by kohlhase** [comment]
I wanted to keep the issue on MMT open, so cc: @tkw1536

**Comment by kohlhase** [comment]
I see more clearly now. Somehow, an old version of the file stex-smglom-module.opt has been installed. Maybe that has something to do with @angerhang's new cpan method?

**Comment by angerhang** [comment]
Yes you are right the plugin should allow us to not include the path and the correct path should really be
```
ext/perl5lib/lib/perl5/LaTeXML/resources/XSLT/
```

**Comment by angerhang** [comment]
Hmm there is probably something wrong with your setup. After `lmh setup --update`, docker seems to be loading the right profile 
`(Loading profile /mounted/lmh/ext/perl5lib/lib/perl5/LaTeXML/resources/Profiles/stex-smglom-module.opt... )`
which has the right stylesheet
```
Hangs-MBP:localmh Hang$ cat ext/perl5lib/lib/perl5/LaTeXML/resources/Profiles/stex-smglom-module.opt
comments =
format = xml
whatsin = fragment
whatsout = document
post =
xmath =
openmath =
pmml =
includestyles =
stylesheet = omdocpost.xsl
nodefaultresources =
preload = [mh]smglom.cls
preload = amsmath
preload = amssymb
#preload = tikz
preload = eurosym
preload = wasysym
preload = multirow
preload = paralist
preload = lststex
preload = lstomdoc
preload = ded
preload = calbf
preload = url
preload = wrapfig
preload = colortbl
preload = [show]ed
```
There are two things we can do:
* Check if in `LaTeXMLsTeX/lib/LaTeXML/resources/Profiles` if the right profiles are there. If yes then proceed to the second step, if not then it means `lmh` might be getting the right version.
* Check if in `mounted/lmh/ext/perl5lib/lib/perl5/LaTeXML/resources/Profiles/` all the profiles have been installed. If yes then everything should theoretically be right, if no then it means `lmh setup --update` is not installing the pulgin at the right place.

**Comment by angerhang** [comment]
I am not sure which old version of ` stex-smglom-module.opt` you are referring to, do you mean the one with `stylesheet = $STEXSTYDIR/../xsl/omdocpost.xsl` in place?

**Comment by kohlhase** [comment]
yes, that. I am currently re-installing completely, and try to see what happens

**Comment by kohlhase** [comment]
hmmmm, that made the problem go away. I wonder what it was, ... sorry for troubling you
