### ISSUE TITLE
add structuring sections to *.ltxml

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#84]
[modules.sty.ltxml](lib/LaTeXML/Package/modules.sty.ltxml)  has nice structural section headings 
```
# =======================================================
# 0. Introduce parameters:                              #
# =======================================================
```
that are helpful for keeping order. We should have them in all ```*.ltxml``` files. Currently they do not even have blank lines (which should also be added), since they are extracted from the DTX files.

**Comment by kohlhase** [comment]
Oh, it would be very good if the sections (the positive ones anyways) would correspond to the ones in the DTX files for sTeX.

**Comment by angerhang** [comment]
Done, closing....
