### ISSUE TITLE
we do not need the paths part in the profiles any more?

### ISSUE THREAD

**Issue by kohlhase** [KWARC/LaTeXML-Plugin-sTeX#9]
is that correct in a plugin?

**Comment by dginev** [comment]
If you put all bindings under Package/ than the paths in the profiles are no longer necessary, correct. Neither will be the ```$STEXSTYDIR``` hack.

**Comment by kohlhase** [comment]
OK, then I will simplify the profiles.

**Comment by kohlhase** [comment]
I assume that we can also find the xslt and schema files.
